version: "3.3"

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '${DOCKER_DB_PORT:-5432}:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data