server:
  port: 8088
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tezbazar
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yml
